--- # Ansible Role [MySQL]: tasks.ubuntu.copy_mysql_config (Axel Pardemann <axelitus@GitHub>)
- name: Copy MySQL configuration
  template: 
    src: "mysqld.cnf.j2"
    dest: "{{ axelitus_mysql_server_conf }}"
    owner: "root"
    group: "root"
  notify:
    - Restart MySQL service